name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - uses: extractions/setup-just@v3
      - name: Run tests
        run: zig build test --summary all

      - name: Run valgrind tests
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
          just test-valgrind

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - name: Build
        run: zig build

  check:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - lint
      - tests
      - build
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJson( needs ) }}
